# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c59508e90cf278f19b1e166d1434281181409744e7cb86ef710464b869ba87bc3b8f91cb7dd37b9dd52880635e5184c4f00c4d4dc1a75c2294cead2338b273

test:
  secret_key_base: a22f1efd52bd6ae3487b7e2ed62768cf963c801b14ebf51671a5daa9acc1c71c63801e806c792618a3e67a4eb7eb8e53b6711ec8b296c98a5778e5d1816b70e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
